### ISSUE TITLE
Missing MAINTAINERS.md file

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website-search#38]
During an evaluation of our repos last week, I noticed this repository does not contain a MAINTAINERS.md file. Our https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md file provides an overview and outline to resolve this.

**Comment by krisfreedain** [comment]
sent request to @ryanbogan for assistance

**Comment by CEHENKLE** [comment]
added maintainers, updated code owners
