### ISSUE TITLE
Requesting Ownership of Repo

### ISSUE THREAD

**Issue by macohen** [opensearch-project/project-website-search#49]
My focus in OpenSearch is on search applications/relevance and there is certainly a need to improve opensearch.org search. There is no owner of this repo at the moment and the opensearch.org search can use some help in search relevance. We may take a look at reworking this feature in the future or evolving and tweaking it to produce better results.

At the very least, this repo needs an owner who can handle managing contributors, maintainers, security, and community involvement.

Please let me know if there are concerns/questions about this. 

@opensearch-project/admin

**Comment by dblock** [comment]
No concerns!
